name: Build ESP32-S3 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/

    - name: Install ESP32 Core
      run: |
        arduino-cli config init
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Detect sketch file
      id: detect_sketch
      run: |
        SKETCH=$(find . -maxdepth 1 -name "*.ino" | head -n 1)
        echo "sketch=$SKETCH" >> $GITHUB_OUTPUT
        echo "Detected sketch: $SKETCH"

    - name: Compile sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32s3 ${{ steps.detect_sketch.outputs.sketch }} --export-binaries

    - name: Rename firmware
      run: |
        mkdir -p output
        BIN_FILE=$(find ./build -name "*.bin" | head -n 1)
        cp "$BIN_FILE" ./output/firmware-esp32s3.bin

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware-esp32s3
        path: ./output/firmware-esp32s3.bin
