name: Build ESP32S3 firmware

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1
      with:
        version: latest

    - name: Install ESP32 Core
      run: |
        arduino-cli config init
        arduino-cli config add board_manager.additional_urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Compile sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32s3 ./main.ino
        mkdir -p output
        cp ./main.ino.*.bin output/firmware.bin

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: esp32s3-firmware
        path: output/firmware.bin
